var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/[[...slugs]]/route.js")
R.c("server/chunks/node_modules_b59742aa._.js")
R.c("server/chunks/node_modules_next_3f08ff81._.js")
R.c("server/chunks/node_modules_@sinclair_typebox_build_esm_cf176f76._.js")
R.c("server/chunks/node_modules_elysia_dist_9130ce2e._.js")
R.c("server/chunks/node_modules_@clerk_backend_dist_6d68d473._.js")
R.c("server/chunks/node_modules_@neondatabase_serverless_index_mjs_2c73916b._.js")
R.c("server/chunks/node_modules_drizzle-orm_15ababe1._.js")
R.c("server/chunks/node_modules_minecraft-server-util_dist_2e45f307._.js")
R.c("server/chunks/node_modules_2daa7fe2._.js")
R.c("server/chunks/[root-of-the-server]__7e0399f2._.js")
R.c("server/chunks/_next-internal_server_app_api_[[___slugs]]_route_actions_678d01c1.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/[[...slugs]]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/[[...slugs]]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
